data:
  dataset: vehicle
  data_dir: ../../SED-single_vehicle-30_sec
  annotations_path: ../../SED-single_vehicle-30_sec/weak_labels.csv
  test_annotations_path: ../../SED-single_vehicle-30_sec/weak_labels_test.csv
  partition: ../../SED-single_vehicle-30_sec/partitions.pkl
  classes:
  - 1
  - 2
  - 5
  - 12
  - 15
  header:
  - filepath_wav_30
  - vehicle_class
  - vehicle_class_combo
  - vehicle_class_base
  - speed
feats:
  duration: 30
  sample_rate: 16000
  n_fft: 2048
  win_length: 2048
  hop_length: 256
  n_mels: 128
  f_min: 0
  f_max: 8000
training:
  batch_size: 8
  lr: 1e-05
  epochs: 50
  num_workers: 4
  seed: 42
  n_frames: 1876
