data:
  dataset: IDMT
  data_dir: ../../IDMT_Traffic
  annotations_path: ../../IDMT_Traffic/annotation/vehicle_train.csv
  test_annotations_path: ../../IDMT_Traffic/annotation/vehicle_test.csv
  partition: ../../IDMT_Traffic/partitions.pkl
  classes:
  - C
  - M
  - T
  header:
  - filename
  - vehicle_class
feats:
  duration: 2
  sample_rate: 22050
  n_fft: 1024
  hop_length: 512
  n_mels: 16
  f_min: 0
  f_max: 8000
training:
  batch_size: 12
  lr: 1e-05
  epochs: 250
  num_workers: 4
  seed: 42
  n_frames: 87
