data:
  dataset: IDMT
  data_dir: ../../IDMT_Traffic
  annotations_path: ../../IDMT_Traffic/annotation/vehicle_train.csv
  test_annotations_path: ../../IDMT_Traffic/annotation/vehicle_test.csv
  partition: ../../IDMT_Traffic/partitions.pkl
  classes:
  - C
  - M
  - T
  header:
  - filename
  - vehicle_class
feats:
  n_mels: 16
  n_filters: 2048
  hop_length: 512
  n_window: 1024
  sample_rate: 22050
  f_min: 0
  f_max: 8000
  duration: 2
training:
  batch_size: 12
  lr: 0.001
  epochs: 100
  num_workers: 4
  seed: 42
  n_frames: 87
