data:
  dataset: vehicle
  basedir: /media/huimin/Backup_03TB_651/single_vehicle-20sec_gap15sec
  annotations_path: /media/huimin/Backup_03TB_651/single_vehicle-20sec_gap15sec/strong_and_weak_labels.csv
  test_annotations_path: null
  npy_path: /media/huimin/Backup_03TB_651/single_vehicle-20sec_gap15sec/npy
  partition: /media/huimin/Backup_03TB_651/single_vehicle-20sec_gap15sec/partitions.pkl
  classes:
  - 1
  - 2
  - 5
  - 12
  header:
  - filename
  - onset
  - offset
  - vehicle_class
  - speed
feats:
  duration: 20
  sample_rate: 16000
  n_fft: 2048
  win_length: 2048
  hop_length: 256
  n_mels: 128
  f_min: 0
  f_max: 8000
training:
  batch_size: 8
  lr: 1e-05
  epochs: 70
  num_workers: 4
  seed: 42
